uint32 LIGHT_STATE_OFF=0
uint32 LIGHT_STATE_RED=1
uint32 LIGHT_STATE_GREEN=2
uint32 LIGHT_STATE_YELLOW=3
uint32 LIGHT_STATE_BLUE=4
uint32 LIGHT_STATE_PURPLE=5
uint32 LIGHT_STATE_CYAN=6
uint32 LIGHT_STATE_WHITE=7

uint32 LIGHT_STATE_RED_FLASH=9
uint32 LIGHT_STATE_GREEN_FLASH=10
uint32 LIGHT_STATE_YELLOW_FLASH=11
uint32 LIGHT_STATE_BLUE_FLASH=12
uint32 LIGHT_STATE_PURPLE_FLASH=13
uint32 LIGHT_STATE_CYAN_FLASH=14
uint32 LIGHT_STATE_WHITE_FLASH=15

# Desired light state
uint32 light_state 0
---
bool success
string message
