int8 LIGHT_STATE_OFF=0
int8 LIGHT_STATE_RED=1
int8 LIGHT_STATE_GREEN=2
int8 LIGHT_STATE_YELLOW=3
int8 LIGHT_STATE_BLUE=4
int8 LIGHT_STATE_PURPLE=5
int8 LIGHT_STATE_CYAN=6
int8 LIGHT_STATE_WHITE=7

int8 LIGHT_STATE_RED_FLASH=9
int8 LIGHT_STATE_GREEN_FLASH=10
int8 LIGHT_STATE_YELLOW_FLASH=11
int8 LIGHT_STATE_BLUE_FLASH=12
int8 LIGHT_STATE_PURPLE_FLASH=13
int8 LIGHT_STATE_CYAN_FLASH=14
int8 LIGHT_STATE_WHITE_FLASH=15

uint32 light_state 0
---
bool success
string message
