# This service is used specifically in the interbotix_perception_modules package
#
# List of ClusterInfo messages. The length of the list should correspond to the
# number of objects seen by the camera

---
interbotix_xs_msgs/ClusterInfo[] clusters
