# This service is used specifically in the interbotix_perception_modules package
#
# Save the latest rgb picture with the specified name
#
# Request consists of:
#   filename : name of file in which to save image including extension (.jpg)
#
# Response consists of:
#    success : boolean indication of service success

string filename
---
bool success
string filepath