# Torque joints on/off

string cmd_type          # set to 'group' if commanding a joint group or 'single' if commanding a single joint
string name              # name of the group if commanding a joint group or joint if commanding a single joint
bool enable              # set to 'true' to torque on or 'false' to torque off
---
