name: build-humble

on:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - humble
  workflow_dispatch:

# Limit jobs run by PRs or branches by cancelling ongoing jobs
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-concurrency-and-the-default-behavior
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  humble:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: main}
          - {ROS_DISTRO: humble, ROS_REPO: testing}
    runs-on: ubuntu-latest
    container: ubuntu:jammy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Prepare Workspace
        run: |
          rm \
            interbotix_ros_common_drivers/COLCON_IGNORE \
            interbotix_ros_xseries/COLCON_IGNORE \
            interbotix_ros_slate/COLCON_IGNORE
      - uses: ros-tooling/setup-ros@v0.7
        with:
          use-ros2-testing: true
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
          package-name:
            interbotix_footswitch_driver
            interbotix_footswitch_msgs
            interbotix_ros_slate
            interbotix_ros_xseries
            interbotix_slate_driver
            interbotix_slate_msgs
            interbotix_xs_msgs
            interbotix_xs_sdk
